# 应用名称
spring:
  application:
  name: blog
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: Abcdefg@1234
    url: jdbc:mysql://192.168.56.101/user_info?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
  aop:
    auto: true
    proxy-target-class: true
  redis:
    port: 6379
    host: 192.168.56.101
    timeout: 1000
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 15MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  mapper-locations: classpath:mapper/*.xml
# 应用服务 WEB 访问端口
server:
  port: 8080



