# 应用名称
spring:
  application:
  name: blog
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blog_new?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
  aop:
    auto: true
    proxy-target-class: true
  redis:
    port: 6379
    host: 127.0.0.1
    timeout: 1000
    password: root
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 15MB
  devtools:
    restart:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: qch223606@163.com
    password: LRYNAFBMZEUQZIRR
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    cache-enabled: true
  mapper-locations: classpath:mapper/*.xml
# 应用服务 WEB 访问端口
server:
  port: 8206

blog:
  length:
    article: 50
    markdown: 50
  mark-days: 7

qiniu:
  access-key: vdOG8OqrElRVUq8Atyttwd0RO6-RgLqeSFwznDjz
  secret-key: C9AzHs3p3nhrHRKdtgsbkEDUcWm8KxQ3wLiEn-PK


